insert into inf_resxkey_value values(1001,'Server','Server',1,'lbl',0,''  );
insert into inf_resxkey_value values(1002,'AccessTypes','Access Types',1,'lbl',0,''  );
insert into inf_resxkey_value values(1003,'AccessDetails','Access Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1004,'Code','Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1005,'Name','Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1006,'AccessAccount','Account Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1007,'AccessAccountDetails','Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1008,'ClientAccounts','Client Accounts',1,'lbl',0,''  );
insert into inf_resxkey_value values(1009,'Action','Action',1,'lbl',0,''  );
insert into inf_resxkey_value values(1010,'Title','Acces Control',1,'lbl',0,''  );
insert into inf_resxkey_value values(1011,'Select','Select',1,'lbl',0,''  );
insert into inf_resxkey_value values(1012,'Logout','Logout',1,'lbl',0,''  );
insert into inf_resxkey_value values(1013,'All','All',1,'lbl',0,''  );
insert into inf_resxkey_value values(1014,'Code','Enter Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1015,'Name','Enter Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1016,'OldPassword','OldPassword',1,'lbl',0,''  );
insert into inf_resxkey_value values(1017,'Password','Password',1,'lbl',0,''  );
insert into inf_resxkey_value values(1018,'Password','Enter Password',1,'rqd',0,''  );
insert into inf_resxkey_value values(1019,'ConfirmPassword','Enter Confirm Password',1,'rqd',0,''  );
insert into inf_resxkey_value values(1020,'ChangePassword','Change Password',1,'lbl',0,''  );
insert into inf_resxkey_value values(1021,'PasswordNotMatch','Password does not match with confirm password',1,'msg',0,''  );
insert into inf_resxkey_value values(1022,'InvalidOldPassword','Entered old password is invalid',1,'msg',0,''  );
insert into inf_resxkey_value values(1023,'ConfirmPassword','Passwort bestätigen',1,'lbl',0,''  );
insert into inf_resxkey_value values(1024,'ClientAccountDetails','Client Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1025,'MPUDetails','Media Paypal UstId Detail',1,'lbl',0,''  );
insert into inf_resxkey_value values(1026,'Servers','Servers',1,'lbl',0,''  );
insert into inf_resxkey_value values(1027,'Clients','Clients',1,'lbl',0,''  );
insert into inf_resxkey_value values(1028,'ClientAccountCode','Client Acccount Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1029,'ClientAccountLicenseKey','License Key',1,'lbl',0,''  );
insert into inf_resxkey_value values(1030,'ClientAccountType','Type',1,'lbl',0,''  );
insert into inf_resxkey_value values(1031,'ClientAccountWebSiteUrl','WebSite Url',1,'lbl',0,''  );
insert into inf_resxkey_value values(1032,'ClientAccountTestWebSiteUrl','Test WebSite Url',1,'lbl',0,''  );
insert into inf_resxkey_value values(1033,'ClientAccountShopName','Shopname',1,'lbl',0,''  );
insert into inf_resxkey_value values(1034,'ClientAccountShopRequired','Shop Required',1,'lbl',0,''  );
insert into inf_resxkey_value values(1035,'ClientAccountShopTime','Shop Time',1,'lbl',0,''  );
insert into inf_resxkey_value values(1036,'ClientAccountStatus','Client Account Status',1,'lbl',0,''  );
insert into inf_resxkey_value values(1037,'ClientAccountLogoRequired','Logo Required',1,'lbl',0,''  );
insert into inf_resxkey_value values(1038,'ClientAccountBusinessType','Business Type',1,'lbl',0,''  );
insert into inf_resxkey_value values(1039,'ClientAccountSalesNo','Sales No',1,'lbl',0,''  );
insert into inf_resxkey_value values(1040,'ClientAccountILNNumber','ILN No',1,'lbl',0,''  );
insert into inf_resxkey_value values(1041,'ClientAccountSalesTaxId','Sales Tax Id',1,'lbl',0,''  );
insert into inf_resxkey_value values(1042,'ClientAccountTaxId','Tax Id',1,'lbl',0,''  );
insert into inf_resxkey_value values(1043,'ClientAccountSSLCertification','SSL Certification',1,'lbl',0,''  );
insert into inf_resxkey_value values(1044,'ClientAccountComments','Comments',1,'lbl',0,''  );
insert into inf_resxkey_value values(1045,'ClientCode','Client Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1046,'ClientName','Client Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1047,'ClientLicense','Client License',1,'lbl',0,''  );
insert into inf_resxkey_value values(1048,'ServerCredentials','Server Credential',1,'lbl',0,''  );
insert into inf_resxkey_value values(1049,'Providers','Providers',1,'lbl',0,''  );
insert into inf_resxkey_value values(1050,'Save','Save',1,'lbl',0,''  );
insert into inf_resxkey_value values(1051,'HostName','Host',1,'lbl',0,''  );
insert into inf_resxkey_value values(1052,'Description','Description',1,'lbl',0,''  );
insert into inf_resxkey_value values(1053,'Gender','Gender',1,'lbl',0,''  );
insert into inf_resxkey_value values(1054,'Designation','Designation',1,'lbl',0,''  );
insert into inf_resxkey_value values(1055,'FirstName','First Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1056,'LastName','Last Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1057,'Edit','Edit',1,'lbl',0,''  );
insert into inf_resxkey_value values(1058,'Address1','Address1',1,'lbl',0,''  );
insert into inf_resxkey_value values(1059,'Address2','Address2',1,'lbl',0,''  );
insert into inf_resxkey_value values(1060,'Address3','Address3',1,'lbl',0,''  );
insert into inf_resxkey_value values(1061,'City','City',1,'lbl',0,''  );
insert into inf_resxkey_value values(1062,'Country','Country',1,'lbl',0,''  );
insert into inf_resxkey_value values(1063,'Fax','Fax',1,'lbl',0,''  );
insert into inf_resxkey_value values(1064,'Email','Email',1,'lbl',0,''  );
insert into inf_resxkey_value values(1065,'AddressType','Address Type',1,'lbl',0,''  );
insert into inf_resxkey_value values(1066,'OtherEmail','Other Email',1,'lbl',0,''  );
insert into inf_resxkey_value values(1067,'ZipCode','Zip Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1068,'Culture','Culture',1,'lbl',0,''  );
insert into inf_resxkey_value values(1069,'Add','Add',1,'lbl',0,''  );
insert into inf_resxkey_value values(1070,'BankDetails','Bank Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1071,'BankName','Bank Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1072,'AccountNumber','Account Number',1,'lbl',0,''  );
insert into inf_resxkey_value values(1073,'AccountHolder','Account Holder',1,'lbl',0,''  );
insert into inf_resxkey_value values(1074,'Address','Address',1,'lbl',0,''  );
insert into inf_resxkey_value values(1075,'BLZ','BLZ',1,'lbl',0,''  );
insert into inf_resxkey_value values(1076,'IBAN','IBAN',1,'lbl',0,''  );
insert into inf_resxkey_value values(1077,'BIC','BIC',1,'lbl',0,''  );
insert into inf_resxkey_value values(1078,'Url','Url',1,'lbl',0,''  );
insert into inf_resxkey_value values(1079,'ServerDetails','Server Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1080,'ClientDetails','Client Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1081,'InforiusDetails','Inforius Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1082,'ContactDetails','Contact Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1083,'AccessTypes','Access Types',1,'lbl',0,''  );
insert into inf_resxkey_value values(1084,'AccessCode','Access Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1085,'AccessName','Access Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1086,'Phone','Phone',1,'lbl',0,''  );
insert into inf_resxkey_value values(1087,'Foundationdate','Foundation Date',1,'lbl',0,''  );
insert into inf_resxkey_value values(1088,'RegistrationNumber','Registration Number',1,'lbl',0,''  );
insert into inf_resxkey_value values(1089,'TaxOffice','Tax Office',1,'lbl',0,''  );
insert into inf_resxkey_value values(1090,'Logo','Logo',1,'lbl',0,''  );
insert into inf_resxkey_value values(1091,'PromotionalBanner','Promotional Banner',1,'lbl',0,''  );
insert into inf_resxkey_value values(1092,'PromotionalText','Promotional Text',1,'lbl',0,''  );
insert into inf_resxkey_value values(1093,'Branches','Branches',1,'lbl',0,''  );
insert into inf_resxkey_value values(1094,'Alignment','Alignment',1,'lbl',0,''  );
insert into inf_resxkey_value values(1095,'Members','Members',1,'lbl',0,''  );
insert into inf_resxkey_value values(1096,'Module','Module',1,'lbl',0,''  );
insert into inf_resxkey_value values(1097,'ModuleItem','Module Item',1,'lbl',0,''  );
insert into inf_resxkey_value values(1098,'ModuleModuleItems','Module/Module Items',1,'lbl',0,''  );
insert into inf_resxkey_value values(1099,'LicenseModuleDetails','License Module Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1100,'LicenseExceeded','Number of License Exceeded',1,'msg',0,''  );
insert into inf_resxkey_value values(1101,'MarketAccountDetails','Market Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1102,'ProviderAccountDetails','Provider Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1103,'ProcessAccountDetails','Process Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1104,'Server','Select Server',1,'rqd',0,''  );
insert into inf_resxkey_value values(1105,'Client','Select Client',1,'rqd',0,''  );
insert into inf_resxkey_value values(1106,'ClienName','Enter Client Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1107,'ValidUntil','Enter Client Valid Until',1,'rqd',0,''  );
insert into inf_resxkey_value values(1108,'ClienCode','Enter Client Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1109,'ClaCode','Enter Client Account Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1110,'ClaValidUntil','Enter Client Account License key',1,'rqd',0,''  );
insert into inf_resxkey_value values(1111,'ClaShopName','Enter  Client Account ShopName',1,'rqd',0,''  );
insert into inf_resxkey_value values(1112,'Claname','Enter Client Account Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1113,'ClaWebSiteUrl','Enter  Client Account WebSiteUrl',1,'rqd',0,''  );
insert into inf_resxkey_value values(1114,'ClaStatus','Select  Client Account Status',1,'rqd',0,''  );
insert into inf_resxkey_value values(1115,'ClaType','Select  Client Account Type',1,'rqd',0,''  );
insert into inf_resxkey_value values(1116,'Culture','Select  Client Account Culture',1,'rqd',0,''  );
insert into inf_resxkey_value values(1117,'Gender','Select Gender',1,'rqd',0,''  );
insert into inf_resxkey_value values(1118,'Designation','Enter Designation',1,'rqd',0,''  );
insert into inf_resxkey_value values(1119,'FirstName','Enter First Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1120,'AccountNumber','Enter Account Number',1,'rqd',0,''  );
insert into inf_resxkey_value values(1121,'AccountHolder','Enter Account Holder',1,'rqd',0,''  );
insert into inf_resxkey_value values(1122,'UserName','Enter User Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1123,'Url','Enter Url',1,'rqd',0,''  );
insert into inf_resxkey_value values(1124,'Market','Select Market',1,'rqd',0,''  );
insert into inf_resxkey_value values(1125,'Provider','Select Provider',1,'rqd',0,''  );
insert into inf_resxkey_value values(1126,'Process','Select Process',1,'rqd',0,''  );
insert into inf_resxkey_value values(1127,'Numeric','Allows numbers only',1,'rqd',0,''  );
insert into inf_resxkey_value values(1128,'LicenseKey','Enter Licesnse Key ',0,'rqd',0,''  );
insert into inf_resxkey_value values(1129,'LicenseModuleModuleItem','Select Module/Module Item',1,'rqd',0,''  );
insert into inf_resxkey_value values(1130,'MediaName','MediaName',1,'lbl',0,''  );
insert into inf_resxkey_value values(1131,'MediaLinkName','MediaLinkName',1,'lbl',0,''  );
insert into inf_resxkey_value values(1132,'Action','Aktion',1,'lbl',0,''  );
insert into inf_resxkey_value values(1133,'Market','Markets',1,'lbl',0,''  );
insert into inf_resxkey_value values(1134,'Process','Process',1,'lbl',0,''  );
insert into inf_resxkey_value values(1135,'MediaLinkDetails','MediaLinkDetail',1,'lbl',0,''  );
insert into inf_resxkey_value values(1136,'MediaName','Please Select Media Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1137,'PaypalDetails','PaypalDetail',1,'lbl',0,''  );
insert into inf_resxkey_value values(1138,'TaxInfoDetails','TaxInfoDetail',1,'lbl',0,''  );
insert into inf_resxkey_value values(1139,'UserName','UserName',1,'lbl',0,''  );
insert into inf_resxkey_value values(1140,'APIUserName','APIUserName',1,'lbl',0,''  );
insert into inf_resxkey_value values(1141,'APIPassword','APIPassword',1,'lbl',0,''  );
insert into inf_resxkey_value values(1142,'APISignature','APISignature',1,'lbl',0,''  );
insert into inf_resxkey_value values(1143,'LowVat','Low Vat',1,'lbl',0,''  );
insert into inf_resxkey_value values(1144,'HighVat','High Vat',1,'lbl',0,''  );
insert into inf_resxkey_value values(1145,'TaxId','TaxId',1,'lbl',0,''  );
insert into inf_resxkey_value values(1146,'UserName','Enter Paypal User Name ',0,'rqd',0,''  );
insert into inf_resxkey_value values(1147,'Password','Enter Paypal Password ',0,'rqd',0,''  );
insert into inf_resxkey_value values(1148,'APIUserName','Enter API UserName',1,'rqd',0,''  );
insert into inf_resxkey_value values(1149,'APIPassword','Enter API Password',1,'rqd',0,''  );
insert into inf_resxkey_value values(1150,'APISignature','Enter API Signature',1,'rqd',0,''  );
insert into inf_resxkey_value values(1151,'Country','Select Country',1,'rqd',0,''  );
insert into inf_resxkey_value values(1152,'LowVat','Enter LowVat',1,'rqd',0,''  );
insert into inf_resxkey_value values(1153,'HighVat','Enter HighVat',1,'rqd',0,''  );
insert into inf_resxkey_value values(1154,'TaxId','Enter TaxId',1,'rqd',0,''  );
insert into inf_resxkey_value values(1155,'MediaLink','Enter MediaLink Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1156,'MediaName','Select Media Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1157,'MediaName','Already Exits Media Id:',1,'msg',0,''  );
insert into inf_resxkey_value values(1158,'ClientTitle','Client Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1159,'AddServer','Add Server',1,'lbl',0,''  );
insert into inf_resxkey_value values(1160,'MacCode','MacCode',1,'lbl',0,''  );
insert into inf_resxkey_value values(1161,'ExpiryDate','ExpiryDate',1,'lbl',0,''  );
insert into inf_resxkey_value values(1162,'Select','auswählen ',0,'lbl',0,''  );
insert into inf_resxkey_value values(1163,'UserName','User ',0,'lbl',0,''  );
insert into inf_resxkey_value values(1164,'Password','Password',1,'lbl',0,''  );
insert into inf_resxkey_value values(1165,'Language','Language',1,'lbl',0,''  );
insert into inf_resxkey_value values(1166,'FillDataErrorMessage','Fill all data',1,'msg',0,''  );
insert into inf_resxkey_value values(1167,'Status','Status',1,'lbl',0,''  );
insert into inf_resxkey_value values(1168,'Status','Select ServerStatus',1,'rqd',0,''  );
insert into inf_resxkey_value values(1169,'AccessType','Access Type',1,'lbl',0,''  );
insert into inf_resxkey_value values(1170,'AddClientAccountDetails','Add Client Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1171,'EditClientAccountDetails','Edit Client Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1172,'ClientTitle','Client Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1173,'AddClientInfo','AddClient',1,'lbl',0,''  );
insert into inf_resxkey_value values(1174,'Clientname','Client',1,'lbl',0,''  );
insert into inf_resxkey_value values(1175,'License','Licence',1,'lbl',0,''  );
insert into inf_resxkey_value values(1176,'License','Enter License',1,'rqd',0,''  );
insert into inf_resxkey_value values(1177,'ClientAccountName','Client Account Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1178,'ClientAccountDetails','Client Account Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1179,'ClientAccountCode','Client Account Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1180,'FillDataErrorMessage','Füllen Sie alle Daten',1,'msg',0,''  );
insert into inf_resxkey_value values(1181,'DomainName','Domain Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1182,'Save','Data Saved Successfully',1,'msg',0,''  );
insert into inf_resxkey_value values(1183,'Password','Enter Password',1,'rqd',0,''  );
insert into inf_resxkey_value values(1184,'Token','Token',1,'lbl',0,''  );
insert into inf_resxkey_value values(1185,'ModuleItem','Module Item',1,'lbl',0,''  );
insert into inf_resxkey_value values(1187,'Title','AccessControls',1,'lbl',0,''  );
insert into inf_resxkey_value values(1188,'CountryDesc','Country Info',1,'lbl',0,''  );
insert into inf_resxkey_value values(1189,'All','Alle',1,'lbl',0,''  );
insert into inf_resxkey_value values(1190,'Alpha2Code','Alpha2Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1191,'Alpha3Code','Alpha3Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1192,'NumericCode','NumericCode',1,'lbl',0,''  );
insert into inf_resxkey_value values(1193,'CurrencySymbol','Symbol',1,'lbl',0,''  );
insert into inf_resxkey_value values(1194,'FillDataErrorMessage','Fill all data correctly',1,'msg',0,''  );
insert into inf_resxkey_value values(1195,'AddCountryInfo','Add Country',1,'lbl',0,''  );
insert into inf_resxkey_value values(1196,'Title','Currency',1,'lbl',0,''  );
insert into inf_resxkey_value values(1197,'CurrencyCode','CurrencyCode',1,'lbl',0,''  );
insert into inf_resxkey_value values(1198,'CurrencySymbol','CurrencySymbol',1,'lbl',0,''  );
insert into inf_resxkey_value values(1199,'CodeMaxMsg','Maximum length is 3',1,'msg',0,''  );
insert into inf_resxkey_value values(1200,'SymbolMaxMsg','Maximum length is 1',1,'msg',0,''  );
insert into inf_resxkey_value values(1201,'SaveSuccess','Data inserted successfully. ',0,'msg',0,''  );
insert into inf_resxkey_value values(1202,'CurrencyCode','Enter Currency Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1203,'CurrencySymbol','Enter Currency Symbol',1,'rqd',0,''  );
insert into inf_resxkey_value values(1204,'ClientAccounts','Client Accounts',1,'lbl',0,''  );
insert into inf_resxkey_value values(1205,'GlobalControl','Global Control',1,'lbl',0,''  );
insert into inf_resxkey_value values(1206,'AccessDetails','Access Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1207,'AddlanguageInfo','Add Language',1,'lbl',0,''  );
insert into inf_resxkey_value values(1208,'LanguageDesc','Language Description',1,'lbl',0,''  );
insert into inf_resxkey_value values(1209,'LanguageCopyType','Language Copy Type',1,'lbl',0,''  );
insert into inf_resxkey_value values(1210,'Source','Source',1,'lbl',0,''  );
insert into inf_resxkey_value values(1211,'Destination','Destination',1,'lbl',0,''  );
insert into inf_resxkey_value values(1212,'Copy','Copy',1,'lbl',0,''  );
insert into inf_resxkey_value values(1213,'Search','Search',1,'lbl',0,''  );
insert into inf_resxkey_value values(1214,'Update','Update',1,'lbl',0,''  );
insert into inf_resxkey_value values(1215,'languageTypeMessage','Please select languagecopyType',1,'lbl',0,''  );
insert into inf_resxkey_value values(1216,'languageMessage','Source and Destination should not be same',1,'lbl',0,''  );
insert into inf_resxkey_value values(1217,'longmessage','Long Message',1,'lbl',0,''  );
insert into inf_resxkey_value values(1218,'Title','Modules',1,'lbl',0,''  );
insert into inf_resxkey_value values(1219,'ApplicationType','Application Type',1,'lbl',0,''  );
insert into inf_resxkey_value values(1220,'AddTableValueInfo','Add Module',1,'lbl',0,''  );
insert into inf_resxkey_value values(1221,'ItemName','Item Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1222,'MultipleAccount','MultipleAccount',1,'lbl',0,''  );
insert into inf_resxkey_value values(1223,'TemplateName','Template Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1224,'TemplateEvent','Template Event',1,'lbl',0,''  );
insert into inf_resxkey_value values(1225,'ApplicationInfo','Application Info',1,'lbl',0,''  );
insert into inf_resxkey_value values(1226,'ApplicationName','Application Name',1,'lbl',0,''  );
insert into inf_resxkey_value values(1227,'Group','Group',1,'lbl',0,''  );
insert into inf_resxkey_value values(1228,'AddModuleItemInfo','Add ModuleItem',1,'lbl',0,''  );
insert into inf_resxkey_value values(1229,'LicenseRequired','License Required',1,'lbl',0,''  );
insert into inf_resxkey_value values(1230,'DefaultModuleItem','Default ModuleItem',1,'lbl',0,''  );
insert into inf_resxkey_value values(1231,'ApplicationName','ApplicationName Reqired',1,'rqd',0,''  );
insert into inf_resxkey_value values(1232,'ApplicationCode','ApplicationCode Reqired',1,'rqd',0,''  );
insert into inf_resxkey_value values(1233,'ServerTitle','ServerCredentials',1,'lbl',0,''  );
insert into inf_resxkey_value values(1234,'TablevalueTitle','Tablevalues',1,'lbl',0,''  );
insert into inf_resxkey_value values(1235,'AddTableValueInfo','Add Tablevalue',1,'lbl',0,''  );
insert into inf_resxkey_value values(1236,'GroupName','GroupName',1,'lbl',0,''  );
insert into inf_resxkey_value values(1237,'MultipleAccount','MultipleAccount',1,'lbl',0,''  );
insert into inf_resxkey_value values(1238,'Help','Help',1,'lbl',0,''  );
insert into inf_resxkey_value values(1240,'ChangePassword','Change Password',1,'lbl',0,''  );
insert into inf_resxkey_value values(1241,'AddClient','Add Client',1,'lbl',0,''  );
insert into inf_resxkey_value values(1242,'EditClient','Edit Client',1,'lbl',0,''  );
insert into inf_resxkey_value values(1243,'PushData','Push Data',1,'lbl',0,''  );
insert into inf_resxkey_value values(1244,'AddServerCredentials','Add Server Credentials',1,'lbl',0,''  );
insert into inf_resxkey_value values(1245,'ClientName','Enter Client Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1246,'ClientCode','Enter Client Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1247,'DomainName','Enter Domain Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1248,'FoundationDate','Enter Foundation Date',1,'rqd',0,''  );
insert into inf_resxkey_value values(1249,'Client','Select Client',1,'rqd',0,''  );
insert into inf_resxkey_value values(1250,'LanguageCode','Language Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1251,'Reset','Reset',1,'lbl',0,''  );
insert into inf_resxkey_value values(1252,'Alpha3Code','Enter Alpha3 Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1253,'NumericCode','Enter Numeric Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1254,'GlobalAccessDetails','Global Access Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1255,'GlobalAccessTypes','Global Access Types',1,'lbl',0,''  );
insert into inf_resxkey_value values(1256,'Alpha2Code','Enter Alpha2 Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1257,'LanguageCode','Enter Language Code',1,'rqd',0,''  );
insert into inf_resxkey_value values(1258,'Language','Enter Language',1,'rqd',0,''  );
insert into inf_resxkey_value values(1259,'Translate','Translate',1,'lbl',0,''  );
insert into inf_resxkey_value values(1260,'Delete','Delete',1,'lbl',0,''  );
insert into inf_resxkey_value values(1261,'SystemLanguage','SystemLanguage',1,'lbl',0,''  );
insert into inf_resxkey_value values(1262,'ModuleTitle','Module',1,'lbl',0,''  );
insert into inf_resxkey_value values(1263,'AddModuleInfo','Add Module',1,'lbl',0,''  );
insert into inf_resxkey_value values(1267,'ApplicationCode','Application Code',1,'lbl',0,''  );
insert into inf_resxkey_value values(1268,'SortOrder','Sort Order',1,'lbl',0,''  );
insert into inf_resxkey_value values(1269,'AddApplication','Add Application',1,'lbl',0,''  );
insert into inf_resxkey_value values(1270,'Token','Enter Token',1,'rqd',0,''  );
insert into inf_resxkey_value values(1271,'ClientAccount','Select Client Account',1,'rqd',0,''  );
insert into inf_resxkey_value values(1272,'ItemName','Enter Item Name',1,'rqd',0,''  );
insert into inf_resxkey_value values(1273,'TemplateName','Enter TemplateName',1,'rqd',0,''  );
insert into inf_resxkey_value values(1274,'TemplateEvent','Enter TemplateEvent',1,'rqd',0,''  );
insert into inf_resxkey_value values(1275,'Notification','Notification Message',1,'lbl',0,''  );
insert into inf_resxkey_value values(1276,'Exist','Already Exist',1,'msg',0,''  );
insert into inf_resxkey_value values(1277,'LongText','Long Text',1,'lbl',0,''  );
insert into inf_resxkey_value values(1278,'ShortText','Short Text',1,'lbl',0,''  );
insert into inf_resxkey_value values(1279,'ShortDesc','Enter Short Text',1,'rqd',0,''  );
insert into inf_resxkey_value values(1280,'AddressDetails','Address Details',1,'lbl',0,''  );
insert into inf_resxkey_value values(1281,'Email','Keine gültig Email Adresse.',1,'vld',0,''  );
insert into inf_resxkey_value values(1282,'Email','Bitte geben Sie Ihre E-Mail-Adresse ein.',1,'rqd',0,''  );
insert into inf_resxkey_value values(1283,'ClientStatus','Client Status',1,'lbl',0,''  );
insert into inf_resxkey_value values(1284,'ClientStatus','Select Client Status',1,'rqd',0,''  );
insert into inf_resxkey_value values(1285,'ConfimClientStatus','Do you want to make Client Status as {0}',1,'msg',0,''  );
insert into inf_resxkey_value values(1286,'ConfimClientAccountStatus','Do you want to make Client Account Status as {0}',1,'msg',0,''  );
insert into inf_resxkey_value values(1287,'LicenseModified','As License is changed,Save the Client Details.',1,'msg',0,''  );
insert into inf_resxkey_value values(1288,'Active','Active',1,'lbl',0,''  );
insert into inf_resxkey_value values(1289,'ClientCode','Client code Should not start wih a digit',1,'vld',0,''  );
insert into inf_resxkey_value values(1290,'Activate','Activate?',1,'lbl',0,''  );
insert into inf_resxkey_value values(1291,'ConformDelete','Do you really want to delete?',1,'msg',0,''  );
insert into inf_resxkey_value values(1292,'DeleteSuccess','Successfully deleted',1,'msg',0,''  );
insert into inf_resxkey_value values(1293,'ConfirmInkRegister','Would You like to Register Inkasso',1,'msg',0,''  );
insert into inf_resxkey_value values(1294,'InkassoStatus','InkassoStatus',1,'lbl',0,''  );
insert into inf_resxkey_value values(1295,'InkassoRegisterDate','InkassoRegisterDate',1,'lbl',0,''  );
insert into inf_resxkey_value values(1296,'Inkasso','Inkasso',1,'lbl',0,''  );
insert into inf_resxkey_value values(1297,'SmtpHost','SMTP Host',1,'lbl',0,''  );
insert into inf_resxkey_value values(1298,'SmtpUser','SMTP User',1,'lbl',0,''  );
insert into inf_resxkey_value values(1299,'SmtpPassword','SMTP Password',1,'lbl',0,''  );
insert into inf_resxkey_value values(1300,'SmtpPort','SMTP Port',1,'lbl',0,''  );
insert into inf_resxkey_value values(1301,'CheckBoxCheck','Please Select atleast one Item To Continue',1,'msg',0,''  );
insert into inf_resxkey_value values(1302,'Close','Close',1,'lbl',0,''  );
insert into inf_resxkey_value values(1303,'Alphanumeric','Please enter only numbers or letters.',1,'vld',0,''  );
